name: generate json map

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - name: node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: generate
        run: node build-data.js

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: data
          force_orphan: true

      - name: purge jsdelivr cache
        run: |
          find dist -type f -name "*.json" | sed 's|^dist/||' | while read -r file; do
            curl -s "https://purge.jsdelivr.net/gh/Argel-H/subs-repo@data/$file"
          done

          find . -type f \( -name "*.yml" -o -name "*.yaml" \) -not -path "./dist/*" -not -path "*/node_modules/*" -not -path "./.git/*" | sed 's|^\./||' | while read -r file; do
            curl -s "https://purge.jsdelivr.net/gh/Argel-H/subs-repo@main/$file"
          done
